baseURL = 'https://yue1124.github.io/hero/'
defaultContentLanguage = 'zh'
theme = 'hero'
enableEmoji = true

[languages]
    [languages.en]
        title = 'Demo'
        description = 'A demo of theme hero'

    [languages.zh]
        title = '样例'
        description = '关于主题hero的样例网站'

[outputs]
    home = ["HTML", "JSON"]

[params]
    author = 'bigyue'
    iconfont = '//at.alicdn.com/t/font_2881911_o39brzj1llb.css'

[params.widgets]
    home = [
        "section",
        "welcome"
    ]
    section = [
        "section"
    ]
    single = [
        "section"
    ]
    term = []
    terms = [
        "section"
    ]

[params.blocks]
    home = [
        "profile"
    ]
    section = [
        "folder"
    ]
    single = [
        "markdown"
    ]
    term = []
    terms = [
    ]

[params.welcome]
    head = '你好呀！^.^'
    body = '这里是Hugo主题hero的样例网站，更多详细信息请查看主题首页。'

[params.profile]
    avatar = '/img/logo.png'
    head = '请随意替换此文本，或者不要'
    [[params.profile.links]]
        url = 'tags'
        text = '标签'
    [[params.profile.links]]
        url = 'categories'
        text = '分类'